### ISSUE TITLE
Build failed on the latest gradle plugin

### ISSUE THREAD

**Issue by bopbi** [akaita/easylauncher-gradle-plugin#37]
suddenly the easylauncher is failed when using android plugin 3.4.1

error log: > 
> Task :common:bundleLibCompileGlobalRelease
> Task :common:bundleLibResGlobalRelease
> Task :app:easylauncherGlobalRc FAILED
> Task :common:bundleLibRuntimeGlobalRelease
> Task :testing:compileGlobalReleaseKotlin
> Task :schema:kaptGenerateStubsGlobalDebugKotlin
>
> FAILURE: Build failed with an exception.
>
> * What went wrong:
> Execution failed for task ':app:easylauncherGlobalRc'.
> java.lang.NullPointerException (no error message)
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

probably this plugin need to be updated with the latest android gradle plugin

**Comment by bopbi** [comment]
the cause probably on 
> Caused by: java.lang.NullPointerException
at com.akaita.android.easylauncher.filter.ColorRibbonFilter.getFont(ColorRibbonFilter.java:173)

**Comment by amccaleb** [comment]
I can repro the NPE using CircleCI and using Android Gradle Plugin 3.4.0, so this doesn't seem entirely tied to the Gradle plugin version.

**Comment by amccaleb** [comment]
Tried to work around the issue by using the customColorRibbons and specifying the textRatio myself. This just moved the NPE to a different area:

https://github.com/akaita/easylauncher-gradle-plugin/blob/master/plugin/src/main/groovy/com/akaita/android/easylauncher/filter/ColorRibbonFilter.java#L92

`Caused by: java.lang.NullPointerException
        at com.akaita.android.easylauncher.filter.ColorRibbonFilter.apply(ColorRibbonFilter.java:92)
        at com.akaita.android.easylauncher.plugin.EasyLauncher.lambda$process$0(EasyLauncher.java:34)
        at com.akaita.android.easylauncher.plugin.EasyLauncher.process(EasyLauncher.java:34)
        at com.akaita.android.easylauncher.plugin.EasyLauncher$process.call(Unknown Source)
        at com.akaita.android.easylauncher.plugin.EasyLauncherTask$_run_closure1$_closure6$_closure8.doCall(EasyLauncherTask.groovy:67)
        at com.sun.proxy.$Proxy89.accept(Unknown Source)
        at com.akaita.android.easylauncher.plugin.EasyLauncherTask$_run_closure1$_closure6.doCall(EasyLauncherTask.groovy:56)
        at com.sun.proxy.$Proxy89.accept(Unknown Source)
        at com.akaita.android.easylauncher.plugin.EasyLauncherTask$_run_closure1.doCall(EasyLauncherTask.groovy:53)
        at com.sun.proxy.$Proxy89.accept(Unknown Source)
        at com.akaita.android.easylauncher.plugin.EasyLauncherTask.run(EasyLauncherTask.groovy:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)`

**Comment by lksnmnn** [comment]
This is basically the same issue I am seeing on the "original" ribbonizer project:
https://github.com/maskarade/gradle-android-ribbonizer-plugin/issues/31

Some change in the Circle CI base image triggered this.

I'll remove ribbons alltogether for now...

**Comment by Alqasrawi** [comment]
Any updates on this issue ? I have the same problem with the latest Android gradle plugin and CircleCi

**Comment by bartsidee** [comment]
encountering the same issue, it seems related to openjdk installation on _alpine_ docker images:
https://github.com/docker-library/openjdk/issues/73

I was able to solve it by installing fontconfig to the docker image used:
`RUN apk --update add fontconfig ttf-dejavu`

**Comment by bopbi** [comment]
thanks for sharing @bartsidee will try it

**Comment by anujmiddha** [comment]
@bartsidee Thanks for sharing. Can you also share where in the circleci config file this goes?

**Comment by lksnmnn** [comment]
I believe he is using a custom docker image based on alpine. So the line he posted is added to his Dockerfile. You can then refer to your custom image in the CircleCI config.

**Comment by anujmiddha** [comment]
Ah got it. Thanks @lksnmnn

**Comment by adrinieto** [comment]
I'm having the same problem. Any updates on this?

**Comment by tlb-miyagiyuki** [comment]
I solved this problem in the CircleCI config. thanks to https://github.com/akaita/easylauncher-gradle-plugin/issues/37#issuecomment-544423985.
I added the following command to job.
```
  steps:
    - run:
        name: add fontconfig for easylauncher
        command: sudo apt-get update && sudo apt-get install -y fontconfig ttf-dejavu
```
I'm using `circleci/android:api-29` docker image.
